export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODS_IN_CAT = 'FETCH_PRODS_IN_CAT';
export const FETCH_DEALS = 'FETCH_DEALS';
export const FETCH_BEST_SELLERS = 'FETCH_BEST_SELLERS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOGIN_USER = 'LOGIN_USER';
